export const VENUE_FULL_NAMES: Record<string, string> = {
    "AAAI": "AAAI Conference on Artificial Intelligence",
    "AAMAS": "International Conference on Autonomous Agents and Multiagent Systems",
    "ACCV": "Asian Conference on Computer Vision",
    "ACL": "Annual Meeting of the Association for Computational Linguistics",
    "ACL Findings": "Findings of ACL",
    "ACNS": "International Conference on Applied Cryptography and Network Security",
    "ACSAC": "Annual Computer Security Applications Conference",
    "AIED": "International Conference on Artificial Intelligence in Education",
    "AISTATS": "International Conference on Artificial Intelligence and Statistics",
    "ANCS": "Symposium on Architectures for Networking and Communications Systems",
    "ASE": "International Conference on Automated Software Engineering",
    "ASIACCS": "ACM Asia Conference on Computer and Communications Security",
    "ASIACRYPT": "International Conference on the Theory and Application of Cryptology and Information Security",
    "ASONAM": "International Conference on Advances in Social Networks Analysis and Mining",
    "ASPLOS": "International Conference on Architectural Support for Programming Languages and Operating Systems",
    "ASRU": "Automatic Speech Recognition & Understanding",
    "AVSS": "IEEE International Conference on Advanced Video and Signal Based Surveillance",
    "BCB": "ACM International Conference on Bioinformatics, Computational Biology and Biomedicine",
    "BIBM": "IEEE International Conference on Bioinformatics and Biomedicine",
    "BIGDATA": "IEEE International Conference on Big Data",
    "Blockchain": "IEEE International Conference on Blockchain",
    "BMVC": "British Machine Vision Conference",
    "CADE": "Conference on Automated Deduction",
    "CASES": "International Conference on Compilers, Architecture, and Synthesis for Embedded Systems",
    "CAV": "International Conference on Computer Aided Verification",
    "CC": "International Conference on Compiler Construction",
    "CCC": "Computational Complexity Conference",
    "CCGRID": "IEEE/ACM International Symposium on Cluster, Cloud and Internet Computing",
    "CCS": "Annual ACM Conference on Computer and Communications Security",
    "CGO": "IEEE/ACM International Symposium on Code Generation and Optimization",
    "CHES": "Conference on Cryptographic Hardware and Embedded Systems",
    "CHI": "ACM Conference on Human Factors in Computing Systems",
    "CIDR": "Conference on Innovative Data Systems Research",
    "CIKM": "International Conference on Information and Knowledge Management",
    "CLOUD": "IEEE International Conference on Cloud Computing",
    "CLUSTER": "IEEE International Conference on Cluster Computing",
    "CODASPY": "Conference on Data and Application Security and Privacy",
    "CODES+ISSS": "International Conference on Hardware/Software Codesign and System Synthesis",
    "CogSci": "Annual Meeting of the Cognitive Science Society",
    "CoNEXT": "International Conference on emerging Networking EXperiments and Technologies",
    "COLING": "International Conference on Computational Linguistics",
    "COLT": "Annual Conference Computational Learning Theory",
    "CONCUR": "International Conference on Concurrency Theory",
    "CONEXT": "Conference on Emerging Network Experiment and Technology",
    "CoNLL": "Conference on Computational Natural Language Learning",
    "CoRL": "Conference on Robot Learning",
    "CPM": "Annual Symposium on Combinatorial Pattern Matching",
    "CRYPTO": "Annual International Cryptology Conference",
    "CSCW": "Conference on Computer Supported Cooperative Work",
    "CSEET": "Conference on Software Engineering Education and Training",
    "CSF": "IEEE Computer Security Foundations Symposium",
    "CVPR": "Computer Vision and Pattern Recognition",
    "DAC": "Design Automation Conference",
    "DASFAA": "International Conference on Database Systems for Advanced Applications",
    "DATE": "Design, Automation, and Test in Europe",
    "DISC": "International Symposium on Distributed Computing",
    "DLT": "International Conference on Developments in Language Theory",
    "DSN": "Dependable Systems and Networks",
    "EACL": "Conference of the European Chapter of the Association for Computational Linguistics",
    "ECAI": "European Conference on Artificial Intelligence",
    "ECCB": "European Conference on Computational Biology",
    "ECCV": "European Conference on Computer Vision",
    "ECOOP": "European Conference on Object-Oriented Programming",
    "ECRTS": "Euromicro Conference on Real-Time Systems",
    "EDBT": "International Conference on Extending Database Technology",
    "EMNLP": "Conference on Empirical Methods in Natural Language Processing",
    "EMNLP Findings": "Conference on Empirical Methods in Natural Language Processing",
    "EMSOFT": "International Conference on Embedded Software",
    "ESA": "European Symposium on Algorithms",
    "ESOP": "European Symposium on Programming",
    "ESORICS": "European Symposium on Research in Computer Security",
    "EURO-PAR": "European Conference on Parallel Processing",
    "EUROCRYPT": "International Conference on the Theory and Application of Cryptographic Techniques",
    "Eurographics": "Annual Conference of the European Association for Computer Graphics",
    "EuroS&P": "European Symposium on Security and Privacy",
    "EuroSys": "European Conference on Computer Systems",
    "EuroVis": "Eurographics Conference on Visualization",
    "FASE": "Fundamental Approaches to Software Engineering",
    "FAST": "USENIX Conference on File and Storage Technologies",
    "FC": "Financial Cryptography and Data Security",
    "FCCM": "IEEE Symposium on Field-Programmable Custom Computing Machines",
    "FM": "International Symposium on Formal Methods",
    "FMCAD": "Formal Methods in Computer-Aided Design",
    "FOCS": "IEEE Annual Symposium on Foundations of Computer Science",
    "FPGA": "Symposium on Field Programmable Gate Arrays",
    "FPL": "International Conference on Field-Programmable Logic and Applications",
    "FSE": "Fast Software Encryption Workshop",
    "FSE/ESEC": "ACM SIGSOFT Conference on the Foundations of Software Engineering",
    "GECCO": "Annual Conference on Genetic and Evolutionary Computation",
    "HiPC": "International Conference on High Performance Computing, Data, and Analytics",
    "HiPEAC": "International Conference on High Performance Embedded Architectures and Compilers",
    "HPCA": "International Symposium on High-Performance Computer Architecture",
    "HPDC": "International Symposium on High-Performance Parallel Distributed Computing",
    "HSCC": "International Conference on Hybrid Systems: Computation and Control",
    "I3D": "ACM Symposium on Interactive 3D Graphics and Games",
    "ICALP": "International Colloquium on Automata, Languages and Programming",
    "ICAPS": "International Conference on Automated Planning and Scheduling",
    "ICASSP": "IEEE International Conference on Acoustics, Speech, and Signal Processing",
    "ICBC": "IEEE International Conference on Blockchain and Cryptocurrency",
    "ICCAD": "International Conference on Computer Aided Design",
    "ICCD": "International Conference on Computer Design",
    "ICCPS": "International Conference on Cyber-Physical Systems",
    "ICCV": "IEEE International Conference on Computer Vision",
    "ICDCS": "IEEE International Conference on Distributed Computing Systems",
    "ICDE": "IEEE International Conference on Data Engineering",
    "ICDM": "IEEE International Conference on Data Mining",
    "ICFP": "ACM SIGPLAN International Conference on Functional Programming",
    "ICLP": "International Conference on Logic Programming",
    "ICLR": "International Conference on Learning Representations",
    "ICMI": "International Conference on Multimodal Interaction",
    "ICML": "International Conference on Machine Learning",
    "ICMR": "International Conference on Multimedia Retrieval",
    "ICN": "Information-Centric Networking",
    "ICNP": "IEEE International Conference on Network Protocols",
    "ICPP": "International Conference on Parallel Processing",
    "ICPR": "International Conference on Pattern Recognition",
    "ICRA": "IEEE International Conference on Robotics and Automation",
    "ICS": "ACM International Conference on Supercomputing",
    "ICSE": "International Conference on Software Engineering",
    "ICSME (ICSM)": "IEEE International Conference on Software Maintenance and Evolution",
    "ICSOC": "International Conference on Service Oriented Computing",
    "ICST": "International Conference on Software Testing, Verification, and Validation",
    "ICWS": "IEEE International Conference on Web Services",
    "ICWSM": "International Conference on Web and Social Media",
    "IISWC": "IEEE International Symposium on Workload Characterization",
    "IJCAI": "International Joint Conference on Artificial Intelligence",
    "IJCAR": "International Joint Conference on Automated Reasoning",
    "IJCNLP": "International Joint Conference on Natural Language Processing",
    "IM": "IFIP/IEEE Symposium on Integrated Network Management",
    "IMC": "ACM/SIGCOMM Internet Measurement Conference",
    "INFOCOM": "IEEE Conference on Computer Communications",
    "InfoVis": "IEEE Information Visualization Conference",
    "InterSpeech": "Conference of the International Speech Communication Association",
    "IPDPS": "IEEE International Parallel and Distributed Processing Symposium",
    "IPMI": "Information Processing in Medical Imaging",
    "IPSN": "International Symposium on Information Processing in Sensor Networks",
    "IROS": "IEEE/RJS International Conference on Intelligent RObots and Systems",
    "ISAAC": "International Symposium on Algorithms and Computation",
    "ISBI": "IEEE International Symposium on Biomedical Imaging",
    "ISCA": "International Symposium on Computer Architecture",
    "ISIT": "International Symposium on Information Theory",
    "ISLPED": "International Symposium on Low Power Electronics and Design",
    "ISMAR": "International Symposium on Mixed and Augmented Reality",
    "ISMB": "Intelligent Systems in Molecular Biology",
    "ISPASS": "IEEE International Symposium on Performance Analysis of Systems and Software",
    "ISSRE": "IEEE International Symposium on Software Reliability Engineering",
    "ISSTA": "International Symposium on Software Testing and Analysis",
    "ISWC": "International Semantic Web Conference",
    "ITS": "International Conference on Augmented Intelligence and Intelligent Tutoring Systems",
    "IUI": "International Conference on Intelligent User Interfaces",
    "KDD": "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    "KR": "International Conference on Principles of Knowledge Representation and Reasoning",
    "LCTES": "ACM SIGPLAN/SIGBED International Conference on Languages, Compilers, and Tools for Embedded Systems",
    "LICS": "ACM/IEEE Symposium on Logic in Computer Science",
    "LREC": "International Conference on Language Resources and Evaluation",
    "MASCOTS": "IEEE/ACM International Symposium on Modeling, Analysis, and Simulation On Computer and Telecommunication Systems",
    "MASS": "IEEE International Conference on Mobile Adhoc and Sensor Systems",
    "MEMSYS": "International Symposium on Memory Systems",
    "MFCS": "International Symposium on Mathematical Foundations of Computer Science",
    "MICCAI": "International Conference on Medical Image Computing and Computer-Assisted Intervention",
    "MICRO": "Annual IEEE/ACM International Symposium on Microarchitecture",
    "MIDDLEWARE": "International Middleware Conference",
    "MLSys": "Conference on Machine Learning and Systems",
    "MM": "ACM International Conference on Multimedia",
    "MMsys": "ACM SIGMM Conference on Multimedia Systems",
    "MobiCom": "Annual International Conference on Mobile Computing and Networking",
    "MobiHoc": "International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing",
    "MobileHCI": "International Conference on Human-Computer Interaction with Mobile Devices and Services",
    "MobiSys": "ACM SIGMOBILE International Conference on Mobile Systems, Applications, and Services",
    "MODELS": "ACM/IEEE International Conference on Model Driven Engineering Languages and Systems",
    "MSR": "IEEE/ACM International Conference on Mining Software Repositories",
    "MSST": "IEEE Conference on Mass Storage Systems and Technologies",
    "NAACL": "North American Chapter of the Association for Computational Linguistics",
    "NAACL/HLT": "North American Chapter of the Association for Computational Linguistics",
    "NDSS": "Network and Distributed System Security Symposium",
    "NeurIPS": "Conference on Neural Information Processing Systems",
    "NIPS": "Conference on Neural Information Processing Systems",
    "NOMS": "IEEE/IFIP Network Operations and Management Symposium",
    "NOSSDAV": "International Workshop on Network and Operating System Support for Digital Audio and Video",
    "NSDI": "USENIX Symposium on Networked Systems Design and Implementation",
    "OOPSLA": "ACM SIGPLAN International Conference on Object-Oriented Programming Systems, Languages, and Applications",
    "OSDI": "USENIX Symposium on Operating Systems Design and Implementation",
    "Pacific Graphics": "Pacific Conference on Computer Graphics and Applications",
    "PACT": "International Conference on Parallel Architectures and Compilation Techniques",
    "PAKDD": "Pacific-Asia Conference on Knowledge Discovery and Data Mining",
    "PAM": "International Conference on Passive and Active Measurement",
    "PERCOM": "Annual IEEE International Conference on Pervasive Computing and Communications",
    "PERFORMANCE": "International Symposium on Computer Modeling, Measurement and Evaluation",
    "PETS": "Proceedings on Privacy Enhancing Technologies",
    "PKC": "International Conference on Theory and Practice of Public Key Cryptography",
    "PKDD": "European Conference on Machine Learning and Knowledge Discovery in Databases",
    "PLDI": "ACM-SIGPLAN Symposium on Programming Language Design and Implementation",
    "PODC": "ACM Symposium on Principles of Distributed Computing",
    "PODS": "ACM SIGACT-SIGMOD-SIGART Symposium on Principles of Database Systems",
    "POPL": "ACM-SIGACT Symposium on Principles of Programming Languages",
    "PPoPP": "ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming",
    "PSB": "Pacific Symposium on Biocomputing",
    "RAID": "International Symposium on Recent Advances in Intrusion Detection",
    "RE": "IEEE International Requirements Engineering Conference",
    "RECOMB": "Annual International Conference on Research in Computational Molecular Biology",
    "RecSys": "ACM Conference on Recommender Systems",
    "RSS": "Robotics: Science and Systems Conference",
    "RTAS": "IEEE Real Time Technology and Applications Symposium",
    "RTSS": "IEEE Real-Time Systems Symposium",
    "S&P": "IEEE Symposium on Security and Privacy",
    "SAC": "ACM Symposium on Applied Computing",
    "SANER": "IEEE International Conference on Software Analysis, Evolution, and Reengineering",
    "SAS": "International Static Analysis Symposium",
    "SC": "International Conference for High Performance Computing, Networking, Storage and Analysis",
    "SCA": "Symposium on Computer Animation",
    "SDM": "SIAM International Conference on Data Mining",
    "SEC (IFIP-SEC)": "IFIP International Information Security Conference",
    "SECON": "Annual IEEE International Conference on Sensing, Communication, and Networking",
    "SenSys": "ACM International Conference on Embedded Networked Sensor Systems",
    "SGP": "Eurographics Symposium on Geometry Processing",
    "SIGCOMM": "ACM SIGCOMM Conference",
    "SIGDIAL": "SIGdial Meetings",
    "SIGGRAPH": "International Conference on Computer Graphics and Interactive Techniques",
    "SIGGRAPH Asia": "ACM SIGGRAPH Conference and Exhibition on Computer Graphics and Interactive Techniques in Asia",
    "SIGIR": "Annual International ACM SIGIR Conference on Research and Development in Information Retrieval",
    "SIGMETRICS": "International Conference on Measurement and Modeling of Computer Systems",
    "SIGMOD": "ACM SIGMOD Conference",
    "SLT": "Spoken Language Technology Workshop",
    "SOCC": "ACM Symposium on Cloud Computing",
    "SoCG": "International Symposium on Computational Geometry",
    "SODA": "ACM-SIAM Symposium on Discrete Algorithms",
    "SOSP": "Symposium on Operating Systems Principles",
    "SOUPS": "Symposium On Usable Privacy and Security",
    "SPAA": "ACM Symposium on Parallelism in Algorithms and Architectures",
    "SRDS": "IEEE International Symposium on Reliable Distributed Systems",
    "STACS": "Symposium on Theoretical Aspects of Computer Science",
    "STOC": "Symposium on the Theory of Computing",
    "SWAT": "Scandinavian Workshop on Algorithm Theory",
    "SYSTOR": "International Systems and Storage Conference",
    "TACAS": "International Conference on Tools and Algorithms for Construction and Analysis of Systems",
    "TCC": "Theory of Cryptography Conference",
    "UAI": "Conference on Uncertainty in Artificial Intelligence",
    "UbiComp": "ACM International Joint Conference on Pervasive and Ubiquitous Computing",
    "UIST": "ACM Symposium on User Interface Software and Technology",
    "USENIX ATC": "USENIX Annual Technical Conference",
    "USENIX FAST": "USENIX Conference on File and Storage Technologies",
    "USENIX NSDI": "Symposium on Networked Systems Design and Implementation",
    "USENIX OSDI": "USENIX Symposium on Operating Systems Design and Implementation",
    "USENIX Security": "USENIX Security Symposium",
    "VEE": "International Conference on Virtual Execution Environments",
    "VIS": "IEEE Visualization Conference",
    "VLDB": "Very Large Data Bases Conference",
    "VMCAI": "International Conference on Verification, Model Checking and Abstract Interpretation",
    "VR": "IEEE Conference on Virtual Reality and 3D User Interfaces",
    "VRST": "ACM Symposium on Virtual Reality Software and Technology",
    "WACV": "IEEE/CVF Winter Conference on Applications of Computer Vision",
    "WADS": "nternational Symposium on Algorithms and Data Structures",
    "WHC/HS": "World Haptics Conference",
    "WiOpt": "International Symposium on Modeling and Optimization in Mobile, Ad-Hoc and Wireless Networks",
    "WiSec": "Conference on Security and Privacy in Wireless and Mobile Networks",
    "WMT": "Conference on Machine Translation",
    "WoWMoM": "IEEE International Symposium on a World of Wireless, Mobile and Multimedia Networks",
    "WSDM": "Web Search and Data Mining",
    "WWW": "The Web Conference"
}
